# These are supported funding model platforms

github: []
patreon: 
open_collective: 
ko_fi: omega_slender
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
